### PR TITLE
Update WW version to 0.8.0

### PR DESCRIPTION
**Pull request by thehomebrewnerd**
### Update WW version to 0.8.0

Update WW requirement to `>=0.8.0` to take advantage of performance improvement in latest version.

### CODE REVIEW

**Comment by tamargrey** [comment]
Latest dependency tests are passing, but minimum dependency tests arent--does the woodwork version need to be updated in those files as well?

**Comment by thehomebrewnerd** [comment]
> Latest dependency tests are passing, but minimum dependency tests arent--does the woodwork version need to be updated in those files (minimum requirements text files) as well?

Maybe so - I thought those other requirements files were supposed to be auto-generated but I haven't really looked closely so might have misunderstood how that works.

**Comment by tamargrey** [comment]
> Maybe so - I thought those other requirements files were supposed to be auto-generated but I haven't really looked closely so might have misunderstood how that works.

Maybe they just get updated automatically on the MachineFL PRs? Seems like there's logic in the minimum dependency checker for that. So if the automated dependency updates had already happened, then the minimum requirements would have been updated?

**Review by tamargrey — APPROVED** [review]
lgtm once the last tests pass!

**Pull request merged**
