### PR TITLE
Fix vulnerability

### PR DESCRIPTION
**Pull request by h2oa**
Hi featuretools security team,

I submitted a report of vulnerability on [huntr.com](http://huntr.com/). I see your product run a bug bounty program on this platform. You can connect to the huntr admin to see details of the report at https://huntr.com/bounties/684bc4d0-3c04-46d6-9076-04bb63f383d0. This pull request is a patch for this vulnerability. Because this is a dangerous vulnerability, please consider it as quickly as possible!

Best regards,
@h2oa

### CODE REVIEW

**Comment by thehomebrewnerd** [comment]
Fixed in #2723

**Comment by h2oa** [comment]
Hi @thehomebrewnerd ,

Can you notify to the admin of huntr.com to consider and change my [report](https://huntr.com/bounties/684bc4d0-3c04-46d6-9076-04bb63f383d0) on huntr.com to valid, this will help me receive a reward commensurate with my efforts to find vulnerabilities. Thanks!

Best regards,
@h2oa

**Comment by thehomebrewnerd** [comment]
@h2oa Thank you for identifying this issue and providing a solution. However, I do not have any involvement with huntr.com, nor does anyone at Alteryx as far as I am aware.

**Comment by h2oa** [comment]
Hi @thehomebrewnerd,

I also don't know how huntr.com works, I know that this open source product is running a bug bounty program on it. Can you contact them by sending a mail to https://huntr.com/contact-us?

Best regards,
@h2oa

**Pull request closed without merging**
