### PR TITLE
Update slack invite link to new

### PR DESCRIPTION
**Pull request by gsheni**

### CODE REVIEW

**Review by thehomebrewnerd — CHANGES_REQUESTED** [review]
Looks like there are two more links in `contributing.md` and one in `help.rst`

**Comment by gsheni** [comment]
@thehomebrewnerd fixed

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd fixed

@gsheni Not sure what happened, but I'm no longer seeing the changes in `README.md`, `setup.cfg`, `config.yml` and `conf.py` that were there before.

**Comment by gsheni** [comment]
@thehomebrewnerd those files have right link (https://github.com/alteryx/featuretools/pull/2040). I accidentally modified all those files in this MR to go back to the old slack link.

**Comment by gsheni** [comment]
@thehomebrewnerd sorry about that. moving too fast. The old links are
 - https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTQ1MjZlOWFmZDk2YzAwMjEzNTkwZTZkN2NmOGFjOGI4YzE5OGMyMGM5NGIxNTE4NjkzYWI3OWEwZjkyZGExYmQ
- https://join.slack.com/t/alteryx-oss/shared_invite/zt-6inxevps-RSbpr9lsACE1kObXz4rIuA

The new link is:
- https://join.slack.com/t/alteryx-oss/shared_invite/zt-182tyvuxv-NzIn6eiCEf8TBziuKp0bNA

**Review by thehomebrewnerd — APPROVED** [review]

**Pull request merged**
