### PR TITLE
Update twitter links in docs

### LINKED ISSUE #1319: Update twitter links in docs
Two twitter links in the docs that should point to https://twitter.com/AlteryxOSS now

### PR DESCRIPTION
**Pull request by gsheni**
- Closes #1319

### CODE REVIEW

**Comment by rwedge** [comment]
There's a second twitter URL in the footer, can you update that as well?

**Comment by gsheni** [comment]
@rwedge Fixed. Here is a preview:
https://featuretools.alteryx.com/en/add_gh_twitter_link/

**Comment by rwedge** [comment]
Looks good, add yourself to the contributor list!

**Review by rwedge — APPROVED** [review]
Looks good

**Pull request merged**
